language: go
sudo: required
go:
- 1.7
- tip
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
- mkdir -p $GOPATH/bin
install:
- make deps
script:
- make ci-test
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make dist
deploy:
  provider: releases

  api_key:
    secure: "omdcGUnAOr7wfP8gQcW+ewtKRrODn31U0MEcqdEwFBXY2bZUKPMywLyL2XWxNwyMpyq8FY+v9iRvoMVLanXkpI8V2LLr0FK/tPINqm00+D03JnQJKgS7WE3H0hHbX/I9vf1AWWSg9g7EOlMu7VhibuH1ixzKoktljzxpOXopAmNjag1j/HM/LB0cJlFZPZiahLs78G3SxvRtf/SxBKZ1UBl2/gPWqgUWB4MELmLEXLV/IOP08+IT/IlrycTC/fU6lTdHbxsgZhNQiSorvTL4mwNVB826G5m5lAKA1fRsXCI28z/ywLb9MMhmAU/R25ElF5lpDe1I1QoVaUGUUup7MEhnopzgcESe6GsOejz23R2plP/VsUKJmDitmGz6sjOYZ0Dw4hzp94vwcXv+mQmKCSEawC/7g9PgYfU/0n0aoX2b45OTMIezmxH/aj9SGDv3ekZmfjbwaqY60pMFs3xYaPwkAcmTb4VonkmoVNv8pIjhMUUKSKeZN2W8r/BYqbdKl0pCN1WoSsID5FHG7Ika+5guM9r+VH2luyBrsjqyP/6gitvmpKMeXMU141l0l8VttdX7rOfpBxoJ2fnLekiWOgqqCtviBCT3Gq7gwVm4f34ypluVMHPHx/c2cwDTLJps2QosqkdaSjjbZEMBG3jDLYvC9YZGK+Z3tK8whWjvajY="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/dist/*.{tar.gz,zip}"
  on:
    repo: budougumi0617/tasks
    tags: true
  skip_cleanup: true
